name: Dependabot npm overrides

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  overrides:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: lreading/dependabot-npm-force-overrides@8181327f59b1946543fec22578c527aeb322129e
        id: overrides
        with:
          github-token: ${{ github.token }}
          package-roots: .
